### ISSUE TITLE
configuration to suppressing logging env-vars and input to tasks

### ISSUE THREAD

**Issue by emilwareus** [backtick-se/cowait#172]
Some things are too sensitive to speak of, so let's not! 

I would like to suppress the logging of environment variables. 
```bash
-- TASK ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   task:       "scheduler-tdivsoqo"
   cluster:    "docker"
   image:      "dockerhub/data-collector-scheduler"
   env:        { GITHUB_TOKEN: "STEAL_THIS_PLZ", BANK_PASSWORD: "a1b2" }
   volumes:    { /var/task: { bind: { src: "xxxr/data_collector", mode: "rw" } } }
-- TASK OUTPUT ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

It would be nice to be able to mask environment variables and other inputs to tasks.

**Comment by johanhenriksson** [comment]
Agreed. We can probably just remove the environment output for now.

It would be nice to have different log levels at some point, this could be reintroduced as debug output later.

**Comment by johanhenriksson** [comment]
I think passing secrets in task inputs and return values should be avoided. Its nice to be able to log them, and we want to be able show them in the dashboard 😄 

Perhaps we should consider adding a way to use Kubernetes secrets for anything sensitive.

**Comment by emilwareus** [comment]
Yes, that should probably be avoided. But it would be great if the env-vars weren't logged :D

**Comment by johanhenriksson** [comment]
Yeah, I will simply remove it for now
