### ISSUE TITLE
RPC call throws key error

### ISSUE THREAD

**Issue by rasmusli** [backtick-se/cowait#308]
When running rpc-calls from child to parent I sporadically get a key-error.  Since I only get it sporadically I suspects is some kind of threading error. 

The parent has the following structure:

```
class ParentTask(Task):
         def init(self):
               self.lock = asyncio.Lock()

          @rpc
          def async def finished(self):
                   async with self.lock:
                        return 1 if (len(queue) == 0) else 0
```

The child tasks calls the parent like such:

```
fin = await self.parent.finished()
```

I am running up to 5 child tasks at the same time. Worth mentioning is that I run several other rpc calls from a few other tasks as well, they all use the same lock though.As mentioned I get this error sporadically:
```
File var/cowait/cowait/tasks/parent_task.py\", line 24, in magic_rpc\   
return await self.call(method, kwargs)  
File \"/var/cowait/cowait/tasks/parent_task.py\", line 18, in call    
return await self.parent.rpc.call(method, args)  
File \"/var/cowait/cowait/network/rpc_client.py\", line 34, in call 
return await asyncio.wrap_future(self.calls[nonce])\nKeyError: 240
```

**Comment by johanhenriksson** [comment]
I suspect this will be fixed by #309, looks like there is a race condition in the RPC call.

**Comment by rasmusli** [comment]
Yes, that looks like it could be it! That would explain the error-trace as well. Do you have an estimation when you will merge this into a new version tag ?

**Comment by johanhenriksson** [comment]
@rasmusli later today :)
